=== jetty/jetty.project/jetty-core/jetty-xml/src/main/resources/org/eclipse/jetty/xml/configure_10_0.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
This is the document type descriptor for the
org.eclipse.jetty.xml.XmlConfiguration class.  It allows a java object to be
configured by with a sequence of Set, Put and Call elements.  These tags are
mapped to methods on the object to be configured as follows:

  <Set  name="Test">value</Set>              ==  obj.setTest("value");
  <Put  name="Test">value</Put>              ==  obj.put("Test","value");
  <Call name="test"><Arg>value</Arg></Call>  ==  obj.test("value");

Values themselves may be configured objects that are created with the
<New> tag or returned from a <Call> tag.

Values are matched to arguments on a best effort approach, but types
my be specified if a match is not achieved.
-->

<!ENTITY % CONFIG "Set|Get|Put|Call|New|Ref|Array|Map|Property">
<!ENTITY % VALUE "#PCDATA|Get|Call|New|Ref|Array|Map|SystemProperty|Env|Property">
<!ENTITY % TYPE_ATTR "type CDATA #IMPLIED " >
<!ENTITY % CLASS_ATTR "class CDATA #IMPLIED" >
<!ENTITY % NAME_ATTR_REQUIRED "name CDATA #REQUIRED" >
<!ENTITY % NAME_ATTR "name CDATA #IMPLIED" >
<!ENTITY % PROPERTY_ATTR "property CDATA #IMPLIED" >
<!ENTITY % DEPRECATED_ATTR "deprecated CDATA #IMPLIED" >
<!ENTITY % DEFAULT_ATTR "default CDATA #IMPLIED" >
<!ENTITY % ID_ATTR "id ID #IMPLIED" >
<!ENTITY % ARG_ATTR "arg CDATA #IMPLIED" >
<!ENTITY % ITEM_ATTR "item CDATA #IMPLIED" >
<!ENTITY % REF_ATTR "refid CDATA #IMPLIED" >
<!ENTITY % ID_ATTR_REQUIRED "id ID #REQUIRED" >

<!--
Configure Element.
This is the root element that specifies the class of object that
can be configured:

    <Configure class="com.acme.MyClass"> ... </Configure>
-->
<!ELEMENT Configure (Id?,Class?,Arg*,(%CONFIG;)*) >
<!ATTLIST Configure %ID_ATTR; %CLASS_ATTR; >


<!--
Set Element.
This element maps to a call to a setter method or field on the current object.
The name and optional type attributes are used to select the setter
method. If the name given is xxx, then a setXxx method is used, or
the xxx field is used of setXxx cannot be found.

A Set element can contain value text and/or the value objects returned
by other elements such as Call, New, SystemProperty, etc.
If no value type is specified, then white
space is trimmed out of the value. If it contains multiple value
elements they are added as strings before being converted to any
specified type.

If the property attribute is set to a property name, then the set is
performed only if the property has a non null value. If the Set element
contains no value then the the property attribute value is used as the set
value.

A Set with a class attribute is treated as a static set method invocation.
-->
<!ELEMENT Set (%VALUE;)* >
<!ATTLIST Set %ID_ATTR; %CLASS_ATTR; %NAME_ATTR_REQUIRED; %TYPE_ATTR; %PROPERTY_ATTR;>


<!--
Get Element.
This element maps to a call to a getter method or field on the current object.
The name attribute is used to select the get method.
If the name given is xxx, then a getXxx method is used, or
the xxx field is used if getXxx cannot be found.
A Get element can contain other elements such as Set, Put, Call, etc.
which act on the object returned by the get call.

A Get with a class attribute is treated as a static get method or field.
-->
<!ELEMENT Get (Id?,Name?,Class?,(%CONFIG;)*) >
<!ATTLIST Get %ID_ATTR; %NAME_ATTR; %CLASS_ATTR; >


<!--
Put Element.
This element maps to a call to a put method on the current object,
which must implement the Map interface. The name attribute is used
as the put key and the optional type attribute can force the type
of the value.

A Put element can contain value text and/or value elements such as Call,
New, SystemProperty, etc. If no value type is specified, then white
space is trimmed out of the value. If it contains multiple value
elements they are added as strings before being converted to any
specified type.
-->
<!ELEMENT Put (%VALUE;)* >
<!ATTLIST Put %NAME_ATTR_REQUIRED; %TYPE_ATTR; >


<!--
Id Element.
This element is the equivalent of the id attribute.
-->
<!ELEMENT Id (%VALUE;)* >


<!--
Name element.
This element is the equivalent of the name attribute.
-->
<!ELEMENT Name (%VALUE;)* >


<!--
Deprecated element.
This element is the equivalent of the deprecated attribute.
-->
<!ELEMENT Deprecated (%VALUE;)* >


<!--
Default element.
This element is the equivalent of the default attribute.
-->
<!ELEMENT Default (%VALUE;)* >


<!--
Class element.
This element is the equivalent of the class attribute.
-->
<!ELEMENT Class (%VALUE;)* >


<!--
Type element.
This element is the equivalent of the type attribute.
-->
<!ELEMENT Type (%VALUE;)* >


<!--
Call Element.
This element maps to an arbitrary call to a method on the current object,
The name attribute and Arg elements are used to select the method.

A Call element can contain a sequence of Arg elements followed by
a sequence of other elements such as Set, Put, Call, etc. which act on any object
returned by the original call:

 <Call id="o2" name="test">
   <Arg>value1</Arg>
   <Set name="Test">Value2</Set>
 </Call>

This is equivalent to:

 Object o2 = o1.test("value1");
 o2.setTest("value2");

A Call with a class attribute is treated as a static call.
-->
<!ELEMENT Call (Id?,Name?,Class?,Arg*,(%CONFIG;)*) >
<!ATTLIST Call %ID_ATTR; %NAME_ATTR; %CLASS_ATTR; %ARG_ATTR; >


<!--
Arg Element.
This element defines a positional or optional named argument for the
Call and New elements. The optional type attribute can force the type
of the value.

An Arg element can contain value text and/or value elements such as Call,
New, SystemProperty, etc. If no value type is specified, then white
space is trimmed out of the value. If it contains multiple value
elements they are added as strings before being converted to any
specified type.
-->
<!ELEMENT Arg (%VALUE;)* >
<!ATTLIST Arg %NAME_ATTR; %TYPE_ATTR; >


<!--
New Element.
This element allows the creation of a new object as part of a
value for elements such as Set, Put, Arg, etc. The class attribute
determines the type of the new object and the contained Arg elements
are used to select the constructor for the new object.

A New element can contain a sequence of Arg elements followed by
a sequence of elements such as Set, Put, Call, etc. elements
which act on the new object:

 <New id="o" class="com.acme.MyClass">
   <Arg>value1</Arg>
   <Set name="test">Value2</Set>
 </New>

This is equivalent to:

 Object o = new com.acme.MyClass("value1");
 o.setTest("Value2");
-->
<!ELEMENT New (Id?,Class?,Arg*,(%CONFIG;)*) >
<!ATTLIST New %ID_ATTR; %CLASS_ATTR; %ARG_ATTR; >


<!--
Ref Element.
This element allows a previously created object to be referenced by id.  The
attribute refid is used to specify the id of another object (the attribute id can
also be used, but it's use is deprecated).
A Ref element can contain a sequence of elements such as Set, Put, Call, etc.
which act on the referenced object.

 <Ref refid="myobject">
   <Set name="Test">Value2</Set>
 </New>
-->
<!ELEMENT Ref (Id?,(%CONFIG;)*) >
<!ATTLIST Ref %ID_ATTR; %REF_ATTR;>


<!--
Array Element.
This element allows the creation of a new array as part of a
value of elements such as Set, Put, Arg, etc. The type attribute determines
the type of the new array and the contained Item elements
are used for each element of the array:

 <Array type="java.lang.String">
   <Item>value0</Item>
   <Item><New class="java.lang.String"><Arg>value1</Arg></New></Item>
 </Array>

This is equivalent to:
 String[] a = new String[] { "value0", new String("value1") };
-->
<!ELEMENT Array (Id?,Type?,Item*) >
<!ATTLIST Array %ID_ATTR; %TYPE_ATTR; %ITEM_ATTR; >


<!--
Map Element.
This element allows the creation of a new map as part of a
value of elements such as Set, Put, Arg, etc. The type attribute determines
the type of the new array and the contained Item elements
are used for each element of the array:

 <Map>
   <Entry>
     <Item>keyName</Item>
     <Item><New class="java.lang.String"><Arg>value1</Arg></New></Item>
   </Entry>
 </Map>

This is equivalent to:
 Map m = new HashMap();
 m.put("keyName", new String("value1"));
-->
<!ELEMENT Map (Id?,Class?,Entry*) >
<!ATTLIST Map %ID_ATTR; %CLASS_ATTR; >
<!ELEMENT Entry (Item,Item) >


<!--
Item Element.
This element defines an entry for the Array or Map Entry elements.
The optional type attribute can force the type of the value.

An Item element can contain value text and/or the value object of
elements such as Call, New, SystemProperty, etc. If no value type
is specified, then white space is trimmed out of the value.
If it contains multiple value elements they are added as strings
before being converted to any specified type.
-->
<!ELEMENT Item (%VALUE;)* >
<!ATTLIST Item %ID_ATTR; %TYPE_ATTR; >


<!--
System Property Element.
This element allows JVM System properties to be retrieved as
part of the value of elements such as Set, Put, Arg, etc.
The name attribute specifies the property name and the optional
default attribute provides a default value.

 <SystemProperty name="Test" default="value" />

This is equivalent to:

 System.getProperty("Test","value");
-->
<!ELEMENT SystemProperty (Id?,Name?,Deprecated*,Default?) >
<!ATTLIST SystemProperty %ID_ATTR; %NAME_ATTR; %DEPRECATED_ATTR; %DEFAULT_ATTR; >


<!--
Environment variable Element.
This element allows OS Environment variables to be retrieved as
part of the value of elements such as Set, Put, Arg, etc.
The name attribute specifies the env variable name and the optional
default attribute provides a default value.

 <Env name="Test" default="value" />

This is equivalent to:

 String v=System.getEnv("Test");
 if (v==null) v="value";
-->
<!ELEMENT Env (Id?,Name?,Deprecated*,Default?) >
<!ATTLIST Env %ID_ATTR; %NAME_ATTR; %DEPRECATED_ATTR; %DEFAULT_ATTR; >


<!--
Property Element.
This element allows arbitrary properties to be retrieved by name.
The name attribute specifies the property name and the optional
default attribute provides a default value.
-->
<!ELEMENT Property (Id?,Name?,Deprecated*,Default?) >
<!ATTLIST Property %ID_ATTR; %NAME_ATTR; %DEPRECATED_ATTR; %DEFAULT_ATTR; >

=== jetty/jetty.project/jetty-demos/jetty-servlet5-demos/jetty-servlet5-demo-jaas-webapp/src/main/config/modules/demo.d/ee11-demo-jaas.xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://eclipse.dev/jetty/configure_10_0.dtd">

<!-- =============================================================== -->
<!-- Configure the demo-jaas webapp                                  -->
<!-- =============================================================== -->
<Configure id='wac' class="org.eclipse.jetty.ee11.webapp.WebAppContext">

  <Set name="contextPath">/ee11-test-jaas</Set>
  <Set name="war"><Property name="jetty.webapps" default="." />/ee11-demo-jaas.war
  </Set>
  <Set name="extractWAR">true</Set>

  <Set name="securityHandler">
    <New class="org.eclipse.jetty.ee11.servlet.security.ConstraintSecurityHandler">
     <Set name="loginService">
       <New class="org.eclipse.jetty.security.jaas.JAASLoginService">
         <Set name="name">Demo JAAS Realm</Set>
         <Set name="loginModuleName">demo</Set>
       </New>
     </Set>
    </New>
  </Set>

</Configure>

=== jetty/jetty.project/jetty-core/jetty-server/src/main/config/etc/jetty.xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">

<!-- =============================================================== -->
<!-- Documentation of this file format can be found at:              -->
<!-- https://eclipse.dev/jetty/documentation/                        -->
<!--                                                                 -->
<!-- Additional configuration files are available in $JETTY_HOME/etc -->
<!-- and can be mixed in. See start.ini file for the default         -->
<!-- configuration files.                                            -->
<!--                                                                 -->
<!-- For a description of the configuration mechanism, see the       -->
<!-- output of:                                                      -->
<!--   java -jar start.jar -?                                        -->
<!-- =============================================================== -->

<!-- =============================================================== -->
<!-- Configure a Jetty Server instance with an ID "Server"           -->
<!-- Other configuration files may also configure the "Server"       -->
<!-- ID, in which case they are adding configuration to the same     -->
<!-- instance.  If other configuration have a different ID, they     -->
<!-- will create and configure another instance of Jetty.            -->
<!-- Consult the javadoc of o.e.j.server.Server for all              -->
<!-- configuration that may be set here.                             -->
<!-- =============================================================== -->
<Configure id="Server" class="org.eclipse.jetty.server.Server">
  <Arg name="threadPool"><Ref refid="threadPool"/></Arg>
  <Arg>
    <New class="org.eclipse.jetty.util.thread.ScheduledExecutorScheduler">
      <Arg name="name"><Property name="jetty.scheduler.name"/></Arg>
      <Arg name="daemon" type="boolean"><Property name="jetty.scheduler.daemon" default="false" /></Arg>
      <Arg name="threads" type="int"><Property name="jetty.scheduler.threads" default="-1" /></Arg>
    </New>
  </Arg>
  <Arg><Ref refid="byteBufferPool"/></Arg>

    <!-- =========================================================== -->
    <!-- Http Configuration.                                         -->
    <!-- This is a common configuration instance used by all         -->
    <!-- connectors that can carry HTTP semantics (HTTP, HTTPS, etc.)-->
    <!-- It configures the non wire protocol aspects of the HTTP     -->
    <!-- semantic.                                                   -->
    <!--                                                             -->
    <!-- This configuration is only defined here and is used by      -->
    <!-- reference from other XML files such as jetty-http.xml,      -->
    <!-- jetty-https.xml and other configuration files which         -->
    <!-- instantiate the connectors.                                 -->
    <!--                                                             -->
    <!-- Consult the javadoc of o.e.j.server.HttpConfiguration       -->
    <!-- for all configuration that may be set here.                 -->
    <!-- =========================================================== -->
    <New id="httpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
      <Set name="secureScheme" property="jetty.httpConfig.secureScheme"/>
      <Set name="securePort" property="jetty.httpConfig.securePort"/>
      <Set name="outputBufferSize" property="jetty.httpConfig.outputBufferSize"/>
      <Set name="outputAggregationSize" property="jetty.httpConfig.outputAggregationSize"/>
      <Set name="requestHeaderSize" property="jetty.httpConfig.requestHeaderSize"/>
      <Set name="responseHeaderSize" property="jetty.httpConfig.responseHeaderSize"/>
      <Set name="sendServerVersion" property="jetty.httpConfig.sendServerVersion"/>
      <Set name="sendDateHeader"><Property name="jetty.httpConfig.sendDateHeader" default="false"/></Set>
      <Set name="headerCacheSize" property="jetty.httpConfig.headerCacheSize"/>
      <Set name="delayDispatchUntilContent" property="jetty.httpConfig.delayDispatchUntilContent"/>
      <Set name="maxErrorDispatches" property="jetty.httpConfig.maxErrorDispatches"/>
      <Set name="persistentConnectionsEnabled" property="jetty.httpConfig.persistentConnectionsEnabled"/>
      <Set name="httpCompliance"><Call class="org.eclipse.jetty.http.HttpCompliance" name="from"><Arg><Property name="jetty.httpConfig.compliance" deprecated="jetty.http.compliance" default="RFC7230"/></Arg></Call></Set>
      <Set name="uriCompliance"><Call class="org.eclipse.jetty.http.UriCompliance" name="from"><Arg><Property name="jetty.httpConfig.uriCompliance" default="DEFAULT"/></Arg></Call></Set>
      <Set name="requestCookieCompliance"><Call class="org.eclipse.jetty.http.CookieCompliance" name="from"><Arg><Property name="jetty.httpConfig.requestCookieCompliance" default="RFC6265"/></Arg></Call></Set>
      <Set name="responseCookieCompliance"><Call class="org.eclipse.jetty.http.CookieCompliance" name="from"><Arg><Property name="jetty.httpConfig.responseCookieCompliance" default="RFC6265"/></Arg></Call></Set>
      <Set name="relativeRedirectAllowed"><Property name="jetty.httpConfig.relativeRedirectAllowed" default="false"/></Set>
      <Set name="useInputDirectByteBuffers" property="jetty.httpConfig.useInputDirectByteBuffers"/>
      <Set name="useOutputDirectByteBuffers" property="jetty.httpConfig.useOutputDirectByteBuffers"/>
    </New>

    <!-- =========================================================== -->
    <!-- Set the handler structure for the Server                    -->
    <!-- =========================================================== -->
    <Set name="defaultHandler">
      <New id="DefaultHandler" class="org.eclipse.jetty.server.handler.DefaultHandler">
        <Arg name="serveFavIcon" type="boolean"><Property name="jetty.server.default.serveFavIcon" default="true"/></Arg>
        <Arg name="showContexts" type="boolean"><Property name="jetty.server.default.showContexts" default="true"/></Arg>
      </New>
    </Set>
    <Set name="handler">
      <New id="Contexts" class="org.eclipse.jetty.server.handler.ContextHandlerCollection">
        <Set name="dynamic" property="jetty.server.contexts.dynamic"/>
      </New>
    </Set>

    <!-- =========================================================== -->
    <!-- extra server options                                        -->
    <!-- =========================================================== -->
    <Set name="stopAtShutdown"><Property name="jetty.server.stopAtShutdown" default="true"/></Set>
    <Set name="stopTimeout"><Property name="jetty.server.stopTimeout" default="5000"/></Set>
    <Set name="dumpAfterStart" property="jetty.server.dumpAfterStart"/>
    <Set name="dumpBeforeStop" property="jetty.server.dumpBeforeStop"/>
    <Set name="tempDirectory" property="jetty.server.tempDirectory"/>

</Configure>

=== jetty/jetty.project/jetty-server/src/main/config/etc/jetty-threadpool-virtual.xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">

<Configure>
  <New id="threadPool" class="org.eclipse.jetty.util.thread.QueuedThreadPool">
    <Set name="name" property="jetty.threadPool.namePrefix" />
    <Set name="minThreads" type="int"><Property name="jetty.threadPool.minThreads" deprecated="threads.min" default="10"/></Set>
    <Set name="maxThreads" type="int"><Property name="jetty.threadPool.maxThreads" deprecated="threads.max" default="200"/></Set>
    <Set name="reservedThreads" type="int"><Property name="jetty.threadPool.reservedThreads" default="-1"/></Set>
    <Set name="idleTimeout" type="int"><Property name="jetty.threadPool.idleTimeout" deprecated="threads.timeout" default="60000"/></Set>
    <Set name="maxEvictCount" type="int"><Property name="jetty.threadPool.maxEvictCount" default="1"/></Set>
    <Set name="detailedDump" type="boolean"><Property name="jetty.threadPool.detailedDump" default="false"/></Set>
    <Get id="namePrefix" name="name" />
    <Call class="java.lang.Thread" name="ofVirtual">
      <Call class="java.lang.Thread$Builder" name="name">
        <Arg>
          <Property name="jetty.threadPool.virtual.namePrefix">
            <Default><Ref refid="namePrefix" />-virtual-</Default>
          </Property>
        </Arg>
        <Arg type="long">0</Arg>
        <Call class="java.lang.Thread$Builder" name="inheritInheritableThreadLocals">
          <Arg type="boolean"><Property name="jetty.threadPool.virtual.inheritInheritableThreadLocals" default="false" /></Arg>
          <Call id="virtualThreadFactory" class="java.lang.Thread$Builder" name="factory" />
        </Call>
      </Call>
    </Call>
    <Call name="setVirtualThreadsExecutor">
      <Arg>
        <Call class="java.util.concurrent.Executors" name="newThreadPerTaskExecutor">
          <Arg><Ref refid="virtualThreadFactory" /></Arg>
        </Call>
      </Arg>
    </Call>
  </New>

  <Call class="org.slf4j.LoggerFactory" name="getLogger">
    <Arg>org.eclipse.jetty</Arg>
    <Call name="info">
      <Arg>Virtual threads are enabled.</Arg>
    </Call>
  </Call>
</Configure>

=== jetty/jetty.project/jetty-gcloud/jetty-gcloud-session-manager/src/main/config-template/etc/sessions/gcloud/session-store.xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">

<Configure id="Server" class="org.eclipse.jetty.server.Server">


  <!-- ===================================================================== -->
  <!-- Configure a factory for GCloudSessionDataStores                       -->
  <!-- ===================================================================== -->
  <Call name="addBean">
   <Arg>
    <New id="sessionDataStoreFactory" class="org.eclipse.jetty.gcloud.session.GCloudSessionDataStoreFactory">
       <Set name="gracePeriodSec" property="jetty.session.gracePeriod.seconds"/>
       <Set name="savePeriodSec" property="jetty.session.savePeriod.seconds"/>
       <Set name="maxRetries" property="jetty.session.gcloud.maxRetries"/>
       <Set name="backoffMs" property="jetty.session.gcloud.backoffMs"/>
       <Set name="namespace" property="jetty.session.gcloud.namespace"/>
       <Set name="host" property="jetty.session.gcloud.host"/>
       <Set name="projectId" property="jetty.session.gcloud.projectId"/>
       <Set name="entityDataModel">
          <New class="org.eclipse.jetty.gcloud.session.GCloudSessionDataStore$EntityDataModel">
              <Set name="kind" property="jetty.session.gcloud.model.kind"/>
              <Set name="id" property="jetty.session.gcloud.model.id"/>
              <Set name="contextPath" property="jetty.session.gcloud.model.contextPath"/>
              <Set name="vhost" property="jetty.session.gcloud.model.vhost"/>
              <Set name="accessed" property="jetty.session.gcloud.model.accessed"/>
              <Set name="lastAccessed" property="jetty.session.gcloud.model.lastAccessed"/>
              <Set name="createTime" property="jetty.session.gcloud.model.createTime"/>
              <Set name="cookieSetTime" property="jetty.session.gcloud.model.cookieSetTime"/>
              <Set name="lastNode" property="jetty.session.gcloud.model.lastNode"/>
              <Set name="lastSaved" property="jetty.session.gcloud.model.lastSaved"/>
              <Set name="expiry" property="jetty.session.gcloud.model.expiry"/>
              <Set name="maxInactive" property="jetty.session.gcloud.model.maxInactive"/>
              <Set name="attributes" property="jetty.session.gcloud.model.attributes"/>
          </New>
       </Set>
    </New>
   </Arg>
  </Call>
  
</Configure>

=== jetty/jetty.project/jetty-server/src/main/config/etc/jetty-http-forwarded.xml
<?xml version="1.0"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">
<Configure id="httpConfig" class="org.eclipse.jetty.server.HttpConfiguration">
  <Call name="addCustomizer">
    <Arg>
      <New class="org.eclipse.jetty.server.ForwardedRequestCustomizer">
        <Set name="forwardedOnly" property="jetty.httpConfig.forwardedOnly"/>
        <Set name="proxyAsAuthority" property="jetty.httpConfig.forwardedProxyAsAuthority"/>
        <Set name="forwardedPortAsAuthority" property="jetty.httpConfig.forwardedPortAsAuthority"/>
        <Set name="forwardedHeader" property="jetty.httpConfig.forwardedHeader"/>
        <Set name="forwardedHostHeader" property="jetty.httpConfig.forwardedHostHeader"/>
        <Set name="forwardedServerHeader" property="jetty.httpConfig.forwardedServerHeader"/>
        <Set name="forwardedProtoHeader" property="jetty.httpConfig.forwardedProtoHeader"/>
        <Set name="forwardedForHeader" property="jetty.httpConfig.forwardedForHeader"/>
        <Set name="forwardedPortHeader" property="jetty.httpConfig.forwardedPortHeader"/>
        <Set name="forwardedHttpsHeader" property="jetty.httpConfig.forwardedHttpsHeader"/>
        <Set name="forwardedSslSessionIdHeader" property="jetty.httpConfig.forwardedSslSessionIdHeader"/>
        <Set name="forwardedCipherSuiteHeader" property="jetty.httpConfig.forwardedCipherSuiteHeader"/>
      </New>
    </Arg>
  </Call>
</Configure>

=== jetty/jetty.project/jetty-demos/jetty-servlet4-demos/jetty-servlet4-demo-jetty-webapp/src/main/config/modules/demo.d/ee8-demo-jetty.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "https://www.eclipse.org/jetty/configure_10_0.dtd">

<!-- ==================================================================
Configure and deploy the test web application
===================================================================== -->

<Configure id="testWebapp" class="org.eclipse.jetty.ee8.webapp.WebAppContext">

  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <!-- Required minimal context configuration :                        -->
  <!--  + contextPath                                                  -->
  <!--  + war OR baseResource                                          -->
  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <Set name="contextPath">/ee8-test</Set>
  <Set name="war"><Property name="jetty.webapps" default="." />/ee8-demo-jetty.war
  </Set>

  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <!-- Optional context configuration                                  -->
  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <Set name="extractWAR">true</Set>
  <Set name="copyWebDir">false</Set>
  <Set name="defaultsDescriptor"><Property name="jetty.home" default="."/>/etc/webdefault-ee8.xml</Set>
  <Set name="overrideDescriptor"><Property name="jetty.webapps" default="." />/ee8-demo-jetty.d/ee8-demo-jetty-override-web.xml
  </Set>
  
  <!-- Enable WebSocket container -->
  <Call name="setAttribute">
    <Arg>org.eclipse.jetty.websocket.jakarta</Arg>
    <Arg type="Boolean">true</Arg>
  </Call>
  
  <Get name="coreContextHandler">
    <Call name="insertHandler">
      <Arg>
        <New class="org.eclipse.jetty.server.handler.gzip.GzipHandler">
          <Set name="minGzipSize">2048</Set>
        </New>
      </Arg>
    </Call>
  </Get>
</Configure>
